Modal-password-assistance
jdomingu98/ft_transcendence_frontend pull request #10
Opened 2024-08-10 11:26 UTC by crist6494

2024-08-22 16:09 UTC, ruzafa8 commented
@crist6494 tiene conflictos esta PR. Hay que resolverlos primero...

2024-08-22 16:12 UTC, crist6494 commented
Vale ahora los soluciono

2024-08-22 17:45 UTC, crist6494 commented
Ya esta solcionado los conflictos

2024-08-23 11:42 UTC, jdomingu98 requested changes
Lo que dije por WhatsApp:

- Muy grande a mi parecer
- No tiene funcionalidad con backend (estaría bien mergear cuando sepamos que funciona todo)
- Traducciones las tienes que hacer tmb, ya que @ruzafa8 termino con esa tarea
- Muchas transiciones y extrañas
- Lo del boton de la "X" para cerrar el modal (por tema UX), que debe estar alineado con la flecha y en el lado opuesto

Deja esta tarea hasta que tengas la del backend lista y este hecha y mergeada la del modal del inicio de sesión

2024-09-08 10:58 UTC, ruzafa8 requested changes

2024-09-08 10:58 UTC, ruzafa8 commented on src/components/common/forms/form-field.js
> +        const type = this.getAttribute('type') || 'type';
Yo no pondría 'type' como por defecto... https://www.w3schools.com/html/html_form_input_types.asp

De los posibles valores podíamos ponerle text por defecto, por ejemplo.

2024-09-08 10:58 UTC, ruzafa8 commented on src/components/common/forms/form-field.js
> +        const text = this.getAttribute('text') || 'text';
Yo no pondría 'text' por defecto, si no mandamos texto, que no se muestre nada, por lo que podríamos poner cadena vacía por defecto
```js
const text = this.getAttribute('text') || '';
```

2024-09-08 10:58 UTC, ruzafa8 commented on src/components/common/forms/form-field.js
> +        const placeholder = this.getAttribute('placeholder') || 'Enter your email or username';
Igual con el placeholder, es preferible que no si no ponemos placeholder, que no se muestre nada... Como mucho pondría un texto traducible

2024-09-08 10:58 UTC, ruzafa8 commented on src/components/common/texts/modal-span-text.js
> +            <span class="text text-start d-flex justify-content-center mb-4 mt-5">${content}</span>
Qué tal poner lo siguiente?
```html
<span class="text text-start d-flex justify-content-center mb-4 mt-5">{{innerHTML}}</span>
```

2024-09-08 10:58 UTC, ruzafa8 commented on src/components/common/texts/modal-span-text.js
> +            <span class="text text-start d-flex justify-content-center mb-4 mt-5">${content}</span>
Ahora, yo no haría un componente tan concreto de esto...

2024-09-08 10:58 UTC, ruzafa8 commented on src/components/app/landing/landing-modal/modal-password-assistance.js
> +                <modal-span-text>Enter your email or username and we’ll send you <br> instructions on how to reset your password.</modal-span-text>
traducir

2024-09-08 10:58 UTC, ruzafa8 commented on src/components/app/landing/landing-modal/modal-password-assistance.js
> +                <modal-span-text>Enter your email or username and we’ll send you <br> instructions on how to reset your password.</modal-span-text>
Además, un componente para este span... no lo haría, pondría aquí <span> directamente con su class...

2024-09-08 10:58 UTC, ruzafa8 commented on src/components/app/landing/landing-modal/modal-password-assistance.js
> +                <modal-h1-text color="var(--app-secondary-color);">Password assistance</modal-h1-text>
traducir

2024-10-12 12:43 UTC, jdomingu98 commented
Cerrada por implementacion en otra rama

2024-10-12 12:43 UTC, closed without merging