Register-modal
jdomingu98/ft_transcendence_frontend pull request #18
Opened 2024-09-06 17:23 UTC by crist6494

2024-09-07 13:34 UTC, jdomingu98 requested changes
Lo que comentamos en la reunion:

- Borde rojo cuando un campo no esta bien relleno
- Opacidad del boton de registro. 2 opciones:
  - Mantener opacidad, pero deshabilitar el boton hasta que esten rellenos los datos. (Validaciones de campos sin rellenar ya no serian necesarios)
  - Quitar opacidad y que tenga un color fijo (el resto igual en principio)
- Falta settear el token en session storage
- Falta redireccion al panel del usuario (perfil)
- Mejorar proceso de validacion del formulario. No esta bien que primero te diga unos errores y que cuando los corrijas te salgan otros en otro lado que antes no te habian dicho nada (ningun formulario de registro funciona así).
- En vez del texto "-OR-", pon "- OR -"
- Añadir padding bottom en los errores de validaciones (esta bastante pegado)

PD: No lo subas todo en un commit y no lo pushees el día del cierre del sprint.

2024-09-08 11:15 UTC, ruzafa8 requested changes

2024-09-08 11:15 UTC, ruzafa8 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +                    if(`${key}` === 'username' || `${key}` === 'checkbox'){
¿Es necesario hacer un
```js
`${key}`
```

Podría valer con:
```js
key === 'username' || key === 'checkbox'
```

2024-09-08 11:15 UTC, ruzafa8 commented on src/components/common/forms/form-field/form-field.js
> +        const text = this.getAttribute('text') || 'text';
Valor por defecto: No pondría "text" como tal... Si no ponemos text, queremos que esté vacío, por lo cual pondría cadena vacía:

```suggestion
        const text = this.getAttribute('text') || '';
```

2024-09-08 11:15 UTC, ruzafa8 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +            return hasErrors ? false : true;
```suggestion
            return !hasErrors;
```

2024-09-08 11:15 UTC, ruzafa8 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +                    if(`${key}` === 'username' || `${key}` === 'checkbox'){
```suggestion
                    if(key === 'username' || key === 'checkbox'){
```

2024-09-08 11:15 UTC, ruzafa8 commented on src/components/common/forms/form-field/form-field.js
> +        const type = this.getAttribute('type') || 'type';
```suggestion
        const type = this.getAttribute('type') || 'text';
```

Este valor lo enchufamos en el atributo type de un input. Si miras la documentación, https://www.w3schools.com/html/html_form_input_types.asp, no se le puede pasar "type" como tal, por defecto si no le pasamos nada es "text", así podríamos respetarlo.

2024-09-08 11:15 UTC, ruzafa8 commented on src/components/common/forms/form-field/form-field.js
> +        const placeholder = this.getAttribute('placeholder') || 'Enter your email or username';
1. Si no ponemos placeholder, lo ideal sería que no se mostrara placeholder.
2. Si le dejasemos un texto, debería de ser un texto traducible (Literal de traducción)

Yo prefiero que sea cadena vacía:
```suggestion
        const placeholder = this.getAttribute('placeholder') || '';
```

2024-09-08 11:15 UTC, ruzafa8 commented on src/components/common/forms/form-field/form-field.js
> +                <label for="${rl}}" class="text-uppercase mb-2 mt-3 text-start">${text}</label>
typo!! Cuidado:
```suggestion
                <label for="${rl}" class="text-uppercase mb-2 mt-3 text-start">${text}</label>
```

2024-09-08 11:15 UTC, ruzafa8 commented on src/components/common/texts/modal-span-text.js
> +            <span class="text text-start d-flex justify-content-center" style="margin-top:${mt}; margin-bottom:${mb};">${content}</span>
```suggestion
            <span class="text text-start d-flex justify-content-center" style="margin-top:${mt}; margin-bottom:${mb};">{{innerHTML}}</span>
```

2024-09-08 11:17 UTC, ruzafa8 commented on src/components/common/texts/modal-span-text.js
> +            <span class="text text-start d-flex justify-content-center" style="margin-top:${mt}; margin-bottom:${mb};">${content}</span>
Yo no tendría este componente!!! Un componente con un span solo... sobra un poco... Pondría directamente el span en el padre

2024-09-08 11:17 UTC, ruzafa8 commented on src/components/common/texts/modal-span-text.js
> +            <span class="text text-start d-flex justify-content-center" style="margin-top:${mt}; margin-bottom:${mb};">${content}</span>
Además... no crearía un atributo que sea mb... usaría algo así como className para pasarle toodo el class que necesite, en vez de un style.

2024-09-08 11:25 UTC, jdomingu98 commented on src/components/common/forms/form-field/form-field.js
> +        const text = this.getAttribute('text') || 'text';
Añado a esto: que es r1? mejor nomenclatura plis

2024-09-10 16:54 UTC, crist6494 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +                    if(`${key}` === 'username' || `${key}` === 'checkbox'){
👍🏻

2024-09-13 18:46 UTC, jdomingu98 requested changes
He revisado un poco por encima y he parado porque sino no termino. Cambia lo que te pongo primero y luego te sigo diciendo.

Si ves cosas similares a las que te he comentado cambialas del tiron para lo alargar esto.

Otras cosas a cambiar:
- Añade algo de padding al icono del ojo de las contraseñas.
- Mensajes de errores algo mas descriptivos. No se lo que es un "Invalid password" cuando me registro
- Consistencia en los errores. De poco e sirve que no me coincidan las contraseñas si luego tambien me dice que es invalida.
- El icono de warning de los mensajes de errores cambialo por uno de error. Además, usa un icono de bootstrap, no el emoji en un span.
- Volviendo al icono del ojo, que cambie cuando habilitas para ver y para no ver

2024-09-13 18:46 UTC, jdomingu98 commented on lib/services/NavigatorService.js
> +        Router.push('/app');
El home no es este, sería "/app/profile/:id", donde ":id" sería el id del usuario

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/modal-card.js
> +
espacios de mas

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/modal-card.js
> +    {
mal formateado

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/modal-card.js
> +        closeEsc = (e) => {
parentesis innecesarios

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/modal-card.js
> +            document.addEventListener('keydown', this.closeEsc);
no se usa addEventListener, en la libreria ya esta implenmentado subscribe

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/modal-card.js
> +                document.removeEventListener('keydown', this.closeEsc);
Lo mismo. Si por un casual @ruzafa8 no implementó el unsuscribe pues que lo añada

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/modal-card.js
> +                <div class="overlay"></div>
Mu cutre esto. Usa la etiqueta dialog para los modales (Investigalo)

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +                    errors[key] = `${capitalizeFirstLetter(key)} is required`;
Mas que hacer una funcion especificamente para cambiar la primera letra, no seria mejor añadirle algo antes.
Ej: "A 'password' is required"

También hay que traducir esto!!

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +                        errors.username = 'Invalid username';
Traduccion

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +                        errors.email = 'Invalid email (name@example.com)';
Traduccion (Lo que esta entre parentesis sobra)

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +                        errors.password = 'Invalid password';
Traduccion

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +                        errors.confirm_password = 'Passwords do not match';
Traduccion

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +                errors.checkbox = 'Please accept the terms to continue.';
Traduccion

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +function capitalizeFirstLetter(str) {
Innecesario

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +
espacio de mas

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +    {
formato

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +            const usernameRegex = /^[a-zA-Z0-9_]{3,20}$/;
Deberia estar en consts.js

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +            const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
Deberia estar en consts.js

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +            const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@.#$!%*?&^])[A-Za-z\d@.#$!%*?&]{8,15}$/;
Deberia estar en consts.js

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +            const usernameRegex = /^[a-zA-Z0-9_]{3,20}$/;
Alinear con el backend el regex si no lo esta

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +            const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
Alinear con el backend el regex si no lo esta

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-modal/register-section/register-section.js
> +            const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@.#$!%*?&^])[A-Za-z\d@.#$!%*?&]{8,15}$/;
Alinear con el backend el regex si no lo esta

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/app/landing/landing-navbar.js
> +            ${this.state.showRegister ? '<modal-card id="modal-register"></modal-card>' : ''}
Estoy casi seguro que se puede gestionar esto con el dialog. Solo es suscribir el boton a un evento de click y darle al dialog el atributo open

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/common/buttons/primary-button.js
> +    styleCSS: `
Todo esto donde se usa?

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/common/buttons/primary-button.js
> -                style=" width:${width}; height:${height}; background-color: ${color}; letter-spacing: 0.1em; font-size: 16px;"
Por que has quitado el letter-spacing y el font-size?

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/common/buttons/primary-button.js
> +        const claseName = this.getAttribute('claseName') || '';
className en lugar de claseName (Pendiente de mirar de como lo usas esto)

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/common/forms/box-form-field/box-form-field.css
> +    color: #8D8DDA;
Usa las variables globales

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/common/forms/box-form-field/box-form-field.css
> +    color: #a8c0f0;
Colores random no. Creo que este color es el del tick del checkbox, asi que usa el color verde de las variables globales

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/common/forms/box-form-field/box-form-field.css
> +    color: #a8c0f0;
Tambien hay un color azul global para el trozo de texto

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/common/forms/form-field/form-field.css
> +    color: #ffffffca;
usa rgba

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/common/forms/form-field/form-field.js
> +            input.type = 'password';
Usa un ternario aqui

2024-09-13 18:46 UTC, jdomingu98 commented on src/components/svg/close-modal.js
> +                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
y este svg? Si es un icono busca en bootstrap el equivalente

2024-09-13 18:46 UTC, jdomingu98 commented on src/i18n/en.json
> +      "OR": "- O R-"
Fallo con los espacios

2024-09-13 18:46 UTC, jdomingu98 commented on src/i18n/en.json
> +      "ACCEPT":"I accept the ",
Este y el de arriba los puedes juntar perfectamente y usar luego ${...}

2024-09-13 18:46 UTC, jdomingu98 commented on src/main.js
> +                { path: '/terms-conditions', component: 'terms-conditions' },
Añade el path del ranking

2024-09-13 18:55 UTC, jdomingu98 commented
La "X" del formulario sigue si estar fija

2024-09-13 20:32 UTC, jdomingu98 commented on src/components/common/buttons/primary-button.js
> +    styleCSS: `
el css me refiero

2024-10-12 14:16 UTC, jdomingu98 commented
Modal hecho.

Cosas faltantes por parte del backend:
- Fixear el endpoint del registro (ya hay una task creada)
- Terminar la confirmacion del registro
- Relacionado con lo primero, mandar literales de traduccion de los endpoint de auth faltantes

2024-10-12 14:20 UTC, jdomingu98 approved these changes
La he hecho yo, asi que obviamente lo veo bien quitando lo comentado que no depende de mi

2024-10-12 14:42 UTC, crist6494 commented
Lo he estado probando y alguna cosas no cuadran: 
-Se puede registrar sin aceptar la casilla de términos y condiciones
-A veces la casilla de términos no funciona correctamente y no se marca o se desmarca
-si el el registro es mayúscula no puedo tener nombre en minúscula? esto es pregunta, porque mis usurios con. nombre Cristian no puedo acceder

-.input:-webkit-autofill {
    -webkit-box-shadow: 0 0 0 1000px transparent inset !important;
    -webkit-text-fill-color: rgba(255, 255, 255, 0.79) !important;
    background-color: transparent !important;
} con esto cuando haces autocompletar se matiene el color dentro del input

El resto lo veo bien

2024-10-12 14:55 UTC, jdomingu98 commented
@crist6494 te contesto así porque no puedo responderte debajo de lo que has puesto:

- No se puede registrar sin pulsar puesto que tiene el campo required en el input. Lo que ves es un bug visual. Si te pasa sin darle siquiera al checkbox le echare un vistazo.
- Lo que pasa con el checkbox es que esta algo bug y no se el motivo. Cuando pulsas en el div va perfecto, pero en el propio checkbox y en el label hace una especie de parpadeo raro.
- El registro no es en mayuscula. Osea, el dato te lo coge bien lo que pasa que se me ha olvidado borrar el estilo.
- No veia necesario lo del autofill la verdad, pero ya que lo has puesto le echo un vistazo
- Cuando escribes o cierras se resetea.

2024-10-12 15:03 UTC, crist6494 commented
Te escribo asi entonces @jdomingu98 xd, vale pues si todavia esta el componente que hice del checbox úsalo si quieres, lo de la máyuscula eso cambiarlo, y yo lo que me refiero  es que si escribes algo en un input o algun mensaje de error, el del  registro por ejemplo y luego me cambio al login y después vuelvo al registro debería estar reiniciado no?, es que ahora mismo se mantiene lo que dejaste escrito.

2024-10-12 15:13 UTC, jdomingu98 commented
@crist6494 he visto tu componente del checkbox y es lo mismo que tengo puesto. Osea un input y un label, nada más. El motivo por el que esta bug es otra cosa

2024-10-12 15:14 UTC, jdomingu98 commented
Lo del formulario que no se borra cuando cambias es una feature. Imaginate que le das sin querer a uno de los botones que te hacen animacion y se te borra lo rellenado

2024-10-12 15:15 UTC, crist6494 commented
@jdomingu98 a vale, de todos modos pondría ese q así se diferencia algo y no tener el checkbox por defecto, pero lo q veas

2024-10-12 16:09 UTC, jdomingu98 commented
@crist6494 revisa de nuevo que ya hice los cambios

2024-10-12 21:09 UTC, ruzafa8 approved these changes
gualililuti

2024-10-12 21:09 UTC, merged