feat: update-password email display
jdomingu98/ft_transcendence_frontend pull request #6
Opened 2024-07-24 11:16 UTC by crist6494

La pantalla esta listo, lo único que no consigo hacer es cambiar los '.' por '*' cuando escribes para que salga en oculto, he dejado un código css comentado y una carpeta font que con html y css normal se aplica ,pero aquí no, supongo que el web-component tendra algo que ver.

2024-07-25 23:44 UTC, jdomingu98 requested changes
Varias cosas:

- Lo de los puntos y asteriscos creo que dependen del navegador que uses o es cosa de bootstrap, pero vaya dejalo asi que no pasa nada
- Por favor, usa los componentes que estan hechos siempre que puedas en lugar de crearte tus estilos css
- No llames a los .css "styles.css" que despues para buscarlos es un rollo. Llamalos siempre como el archivo js asociado. Tienes varios ejemplos por ahí
- Lo del fontello no se para que lo quieres sinceramente no lo veo necesario para lo simple que es la pagina, a no ser que sea algo estilo un ojo para consultar la contraseña que se pone. En caso de ser eso, tampoco iria en el sitio que lo has puesto y seguramente no tendrías que ni descargartelo.
- Ojo con el linter!!! Antes de ghacer commits lanza el comando que tienes en el package.json (npm run lint)
- El boton del formulario de sale de la card al hacerlo algo pequeño
- Siempre que puedas prioriza la propiedad de bootstrap al estilo css, haciendo los cambios sobre el componente de bootstrap. Esto es más que nada por el punto de usar bootstrap (En temas de ahorro de importacion de ficheros daria algo igual porque la carga se haría al html y no al css, siendo el primero mas pesado que de costumbre)

2024-07-25 23:44 UTC, jdomingu98 commented on src/pages/update-password/styles.css
> +    }
Para que necesitas esto exactamente?

2024-07-25 23:44 UTC, jdomingu98 commented on src/pages/update-password/styles.css
> +    color: #ABD9D9;
Siempre que necesites un color comprueba las variable globales css por si esta ya. Si la vas a necesitar en varios sitios y no esta añadida, crea una variable tu

2024-07-26 15:03 UTC, crist6494 commented on src/pages/update-password/styles.css
> +    }
esto servia para cambiar los . por * pero solo me funciona con html css normal ,al hacer lo del render con js no funciona.

2024-08-06 20:41 UTC, ruzafa8 approved these changes
Todo bien por aquí, solo una sugerencia que deberías de aplicar. Añadirle una etiqueta form.

2024-08-06 20:41 UTC, ruzafa8 commented on src/pages/update-password/UpdatePassword.js
> +                            <input type="password" id="new-password" name="new-password">
Los inputs suelen estar encerrados en una etiquta `<form>`...
Aunque no haga nada visual, `<form>` ayuda a identificar que nos encontramos en un formulario. Le da más calidad al HTML.
Esta etiqueta form debería de agrupar a ambos inputs y el botón de confirmación, así los asociamos de alguna forma.

Además, nos será útil para el futuro, cuando el formulario se rellene de verdad y tenga que enviar datos al backend...

2024-08-06 20:42 UTC, ruzafa8 commented on src/main.js
> +    { path: '/update-password', component: 'update-password' },
Tengo una tarea que mueve este routes de sitio, por lo que no tengo en cuenta la existencia de esto. El último que mergee tiene que acordarse de meter esto en el otro sitio.

2024-08-10 10:48 UTC, jdomingu98 approved these changes
Todo bien en principio. Mas adelante mirame el tema de estilos, a ver si se puede reducir

2024-08-10 10:48 UTC, merged